local L = AceLibrary("AceLocale-2.2"):new("XLoot")

L:RegisterTranslations("koKR", function()
	return {
		catSnap = "프레임 동작",
		catLoot = "전리품 동작",
		catFrame = "프레임 설정",
		catInfo = "전리품 정보",
		catGeneralAppearance = "일반적인 외관",
		catFrameAppearance = "프레임 외관",
		catLootAppearance = "전리품 외관",
		catExtras = "기타",
		
		optLock = "프레임 고정",
		optOptions = "GUI 설정",
		optBehavior = "동작 설정",
		optCursor = "커서에 XLoot 프레임 스냅",
		optSmartsnap = "똑똑한 커서 스냅핑",
		optSnapoffset = "스냅 위치",
		optCollapse = "전리품 버튼 자동 숨김",
		optDragborder = "테두리 드래그",
		optLootexpand = "프레임 넓이 자동 조절",
		optAltoptions = "알트+우클릭 메뉴 표시",
		optSwiftloot = "쉬프트 루팅시 프레임 미표시",
		optQualitytext = "아이템 품질 글자 표시",
		optInfotext = "아이템 정보 글자 표시",
		optLinkAll = "모두 링크 버튼",
		optLinkAllVis = "표시: ",
		optLinkAllThreshold = "모두 링크 제한",
		optLinkAllChannels = "항상 링크...",
		optAppearance = "외형",
		optQualityborder = "테두리 품질에 따른 색상화",
		optQualityframe = "배경 품질에 따른 색상화",
		optLootqualityborder = "전리품 테두리 품질에 따른 색상화",
		optBgcolor = "프레임 배경 색상",
		optBordercolor = "프레임 테두리 색상",
		optTexColor = "전리품 아이콘 품질 색상화",
		optHighlightLoot = "전리품 품질 강조",
		optHighlightThreshold = "전리품 강조 경계", 
		optLootbgcolor = "전리품 배경 색상",
		optLootbordercolor = "전리품 테두리 색상",
		optInfoColor = "정보 글자 색상",
		optScale = "크기",
		optAdvanced = "추가 설정",
		optDebug = "디버그 메세지",
		optDefaults = "기본 설정 초기화",
		
		descLock = "전리품 프레임을 움직일 수 없도록 합니다.",
		descOptions = "설정 메뉴를 표시합니다.",
		descBehavior = "XLoot 동작을 변경합니다.",
		descCursor = "전리품 루팅시 항상 커서에 전리품 프레임을 위치시킵니다.",
		descSmartsnap = "아이템 획득에 따라 리스트가 변경될 때 커서 위치에 수직방향으로 전리품 프레임을 위치시킵니다. 프레임이 이리저리 돌아다니지 않습니다.",
		descSnapoffset = "첫번째 전리품 아이콘의 가운데에서 스냅 동작의 수평 거리를 설정합니다.",
		descCollapse = "획득한 (빈)버튼을 숨기고 스냅 설정이 활성화 되어 있다면 다음 프레임에 커서를 위치시킵니다.",
		descDragborder = "전리품 프레임을 버튼 대신 프레임의 테두리를 드래그하여 이동시키는 것을 허용합니다.",
		descLootexpand = "전리품 이름에 따라 프레임 넓이를 변경합니다.",
		descAltoptions = "ALT+우클릭으로 XLoot 메뉴를 표시합니다. 다른 애드온 사용시 혼동되지 않도록 비활성화 할 수 있습니다.",
		descSwiftloot = "Attempts to find out when loot is being shift-rightclick-looted, and never shows the frame if there is space for all items. Should reduce lag when shift-looting, disable if you run into problems.",
		descQualitytext = "아이템의 품질을 가진 아이템의 이름 위에 구분선을 추가하여 표시합니다.",
		descInfotext = "아이템 정보를 가진 아이템의 이름 아래 구분선을 추가하여 표시합니다.",
		descLinkAll = "모든 버튼을 링크합니다. 버튼은 현재 열린 전리품을 알릴 수 있는 모든 이용가능한 채널 메뉴를 표시합니다.",
		descLinkAllVis = "링크시 모든 버튼을 표시합니다.",
		descLinkAllThreshold = "제한 이상의 아이템만 링크합니다.",
		descLinkAllChannels = "모두 링크를 좌클릭 시 항상 해당 채널에 링크합니다. |cFFFF0000체크 해제 시, 모두 링크 메뉴를 표시합니다.|r",
		descAppearance = "각 전리품 버튼 XLootFrame의 색상, 크기, 스킨을 설정합니다.",
		descQualityborder = "아이템 품질 순위에 따른 전리품 프레임의 테두리 색상입니다.",
		descQualityframe = "아이템 품질 순위에 따른 전리품 프레임의 배경 색상입니다.",
		descLootqualityborder = "품질에 따른 전리품 테두리 색상을 사용합니다.",
		descHighlightLoot = "품질에 따른 각 전리품 프레임을 강조합니다.",
		descHighlightThreshold = "전리품 창을 강조할 최하 품질입니다.",
		descBgcolor = "전리품 프레임의 배경 색상을 변경합니다.",
		descBordercolor = "프레임의 테두리 색상을 변경합니다.",
		descTexColor = "품질에 따른 실제 아이템 아이콘/텍스쳐의 테두리 색상을 변경합니다.",
		descLootbgcolor = "모든 전리품 아이템의 배경을 변경합니다.",
		descLootbordercolor = "모든 전리품 아이템의 테두리 색상을 변경합니다.",
		descInfoColor = "정보 글자의 색상을 변경합니다.",
		descScale = "전리품 프레임의 크기입니다.",
		descAdvanced = "Options you may not want to mess with, but can anyway.",
		descDebug = "디버그 메세지를 표시합니다.",
		descDefaults = "모든 설정을 기본 상태로 초기화 합니다.",
		
		qualityQuest = "퀘스트 아이템",
		
		guiTitle = "XLoot 설정",
		
		itemWeapon = "무기",
		
		evHerbs = "약초채집",
		evOpenNT = "열기 - 텍스트 없음",
		evOpen = "열기",
		
		linkallloot = "모두 링크...",
		linkallchanneldesc = "모두 링크를 좌클릭 했을 때 %s 에 자동으로 전리품을 링크합니다.",
	}
end)